<?php
/*
 * Writes the redirects from app/redirects.php into public/.htaccess (block between the BEGIN/END markers)
 * and into docs/redirects.md. Run after every change of app/redirects.php:
 *
 *   php tools/sync-redirects.php
 */
declare(strict_types=1);

$root = dirname(__DIR__);
$map = require "$root/app/redirects.php";

$rules = [];
$rows = [];
foreach ($map as $old => $new) {
    if ($old === '/index.php') { // handled by the PHP router only: in .htaccess it would loop with the front-controller rewrite
        $rows[] = "| `$old` | `$new` (jen PHP router) |";
        continue;
    }
    $pattern = '^' . ltrim(preg_quote(rtrim($old, '/'), '#'), '/') . '/?$';
    $pattern = str_replace('\\-', '-', str_replace('\\/', '/', $pattern));
    $flags = str_contains($new, '#') ? 'R=301,L,NE' : 'R=301,L';
    $rules[] = "  RewriteRule $pattern $new [$flags]";
    $rows[] = "| `$old` | " . (str_starts_with($new, 'http') ? "`$new`" : "`$new`") . ' |';
}
$block = "  # BEGIN redirects (generated by tools/sync-redirects.php from app/redirects.php)\n" . implode("\n", $rules) . "\n  # END redirects";

$file = "$root/public/.htaccess";
$ht = (string) file_get_contents($file);
if (str_contains($ht, '# BEGIN redirects')) {
    $ht = preg_replace('/  # BEGIN redirects.*?# END redirects/s', str_replace('\\', '\\\\', $block), $ht, 1);
} else {
    $ht = str_replace("  # Existing files and folders", "$block\n\n  # Existing files and folders", $ht);
}
file_put_contents($file, $ht);

$md = "# Přesměrování ze starého webu (Joomla, záloha 19. 2. 2024)\n\n"
    . "Zdroj: `app/redirects.php`. Po úpravě spusťte `php tools/sync-redirects.php`, aktualizuje se tento soubor i blok v `public/.htaccess`.\n"
    . "Přesměrování (301) obsluhuje i PHP router, takže fungují i bez `.htaccess`. Statický náhled na GitHub Pages je nahrazuje stránkami s meta refresh.\n\n"
    . "| Starý odkaz | Nový odkaz |\n|---|---|\n" . implode("\n", $rows) . "\n\n"
    . "## Adresy, které se nemění\n\n"
    . "Tyto adresy existují i v novém webu, chybějící lomítko na konci doplní router přesměrováním 301:\n\n"
    . "`/o-nas`, `/kontakt`, `/reference`, `/vzorkovniky` a `/reference/<alias>` (hotel-four-season-praha, hotel-le-palais-praha, hotel-corinthia-tower-praha, hotel-1-republika-praha, palac-u-kocku-praha, hotel-aqua-praha-pruhonice, hotel-international-brno, ostatni-realizace).\n\n"
    . "## Poznámky\n\n"
    . "- Tvary adres vychází z aliasů menu a článků v dumpu (`ij7hd_menu`, `ij7hd_content`) a z přístupových logů 15.–18. 2. 2024. Tabulka `ij7hd_redirect_links` (Joomla) je prázdná.\n"
    . "- `/prodej-metraze/maloobchodni-prodej` byl nepublikovaný, přesměrování vede na Látky a metráž.\n"
    . "- Statické soubory ze starého webu (`/images/...`, `/media/com_dropfiles/...`) se nepřenášejí. Staré PDF mají nové adresy v `/downloads/vzorkovniky/`.\n";
file_put_contents("$root/docs/redirects.md", $md);
echo count($map) . " redirects written\n";
